### ISSUE TITLE
Fail to run

### ISSUE THREAD

**Issue by nguyentrihai93** [TianzhenLi/Intelligent-Intersection#3]
I follow the link here: https://www.jianshu.com/p/3f5b817ff62f

Then I can run the examples in plexe-pyapi. However, when I ran the simulations in this repo. It's failed.

Terminal:
traci.exceptions.FatalTraCIError: connection closed by SUMO

SUMO:
----------------------------------------------------------------------------------------
Loading configuration... done.
***Starting server on port 49243 ***
Loading net-file from 'traditional_traffic.net.xml'... done (8ms).
Loading done.
Error: Unknown car following model 'CC' when parsing vtype 'vtypeauto'
Quitting (on error).
Simulation started with time: 0.00
Error: tcpip::Storage::readIsSafe: want to read 4 bytes from Storage, but only 3 remaining
Quitting (on error).
----------------------------------------------------------------------------------------

**Comment by nguyentrihai93** [comment]
Which version of SUMO are you using?

**Comment by TianzhenLi** [comment]
I introduced how to install SUMO in the README.md file, and you can refer to it.

**Comment by TianzhenLi** [comment]
My version is version 1.4.0

**Comment by nguyentrihai93** [comment]
I still had the above issue.

**Comment by TianzhenLi** [comment]
You put 'plexe' and other programs in a folder, and try to see if it succeeds. I have never had such an error.

**Comment by HappyDay-design** [comment]
> I follow the link here: https://www.jianshu.com/p/3f5b817ff62f
> 
> Then I can run the examples in plexe-pyapi. However, when I ran the simulations in this repo. It's failed.
> 
> Terminal: traci.exceptions.FatalTraCIError: connection closed by SUMO
> 
> ## SUMO:
> ## Loading configuration... done.
> ***Starting server on port 49243 ***
> Loading net-file from 'traditional_traffic.net.xml'... done (8ms).
> Loading done.
> Error: Unknown car following model 'CC' when parsing vtype 'vtypeauto'
> Quitting (on error).
> Simulation started with time: 0.00
> Error: tcpip::Storage::readIsSafe: want to read 4 bytes from Storage, but only 3 remaining
> Quitting (on error).

Hello Hai. Did you fix it?
